name       : hyphen-fr
version    : 3.0
release    : 1
source     :
    - https://grammalecte.net/download/fr/hyph-fr-v3.0.zip : c36e530bbd12d7b36b1238feaf4055dcb05fee0e139ed441953557857de4f363
homepage   : https://grammalecte.net/
license    : LGPL-2.0-or-later
component  : office
summary    : French hyphenation rules
description: |
    French hyphenation rules.
rundeps    :
    - hyphen
install    : |
    install -Dm00644 hyph_fr.dic $installdir/usr/share/hyphen/hyph_fr_FR.dic

    pushd $installdir/usr/share/hyphen/
        fr_FR_aliases="fr_BE fr_CA fr_CH fr_LU fr_MC"
        for lang in ${fr_FR_aliases}; do
            ln -s hyph_fr_FR.dic hyph_${lang}.dic
        done
    popd
